### PR TITLE
Appropriate timer method for current OS and Python version

### LINKED ISSUE #1: optimize-later is incompatible with Python3.8
Since `time.clock` method was removed in Python 3.8, this package became incompatible. Attempting to use this in Python 3.8 results in error: `AttributeError: module 'time' has no attribute 'clock'`

Example code:

```
from optimize_later import optimize_later, register_callback
import time

### Basic usage.
with optimize_later('test_block', 0.2):
    # potentially slow block of code...
    time.sleep(1)```

### PR DESCRIPTION
**Pull request by raiyankamal**
This PR attempts to fix #1

### CODE REVIEW

**Review by quantum5 — CHANGES_REQUESTED** [review]
Thank you for your contribution. However, `process_time` is not the right timer to use here. The actual desired timer is `monotonic`, which was available since Python 3.3. The only reason it wasn't used was for Python 2 compatibility, but that is no longer a concern.

**Comment by raiyankamal** [comment]
Responded your code change request. Please check.

**Comment by quantum5** [comment]
@raiyankamal What I meant was just using `time.monotonic` unconditionally on all platforms, now that it is available. There shouldn't be any logic to select timers on python 3.

**Comment by raiyankamal** [comment]
I adjusted the code to use `monotonic`. I cannot test on Windows, so I'm not sure if I should remove the check with `os.name == 'nt'`. If you are willing to test on Windows, I can make another commit that will replace this line with:

```
timer = time.monotonic
```

On a separate note, `monotonic` is available since 3.3, are you dropping support for all previous Python versions?

**Comment by quantum5** [comment]
Upon further reflection, the best choice would be to use `time.perf_counter`, which should be the best for this task. I am going to drop support for python 2 due to its EOL status as well as python < 3.3. I'll make a PR that changes the CI.

**Comment by raiyankamal** [comment]
Makes sense. Sent another commit with `perf_counter` and also removed the check for `os.name == 'nt'`.

**Comment by quantum5** [comment]
Okay, I made #3 which updated the test matrix. To make python 3.8 pass, I applied your change and inlined the variable. I hope you don't mind.

**Comment by raiyankamal** [comment]
That's fine. Would you be able to do a pip release soon? That'll help us a lot.

**Comment by quantum5** [comment]
@raiyankamal Released v0.3 on PyPI.

**Comment by quantum5** [comment]
The problem has been fixed in f79ac251c5b7df999e1b557e2d56d3635642bea6.

**Pull request closed without merging**
